### ISSUE TITLE
More interactiveness for the HTML version

### ISSUE THREAD

**Issue by rafbuff** [nature-of-code/The-Nature-of-Code-archive#192]
The HTML version has a few advantages over the PDF as it can provide live examples. With one additional feature, you can make it an interactive, responsive tutorial: put the code into an editor frame, so that people can tweak it with immediate results.

**Comment by shiffman** [comment]
Working on a new build system here! https://github.com/nature-of-code/noc-book-2

Everything will be p5.js so hopefully there will opportunities to improve the interactivity features.
