### ISSUE TITLE
Missing MathML/SVGs in section 2.2, HTML only

### ISSUE THREAD

**Issue by pamelafox** [nature-of-code/The-Nature-of-Code-archive#355]
I'm not sure if there's something missing under the Or or if the wording has just surprised me:
https://www.dropbox.com/s/ahkg5ipxn4a7ry1/Screenshot%202014-02-07%2013.49.06.png

**Comment by shiffman** [comment]
This issue is (hopefully!) no longer relevant with the new build system in https://github.com/nature-of-code/noc-book-2
